import numpy as np
import utils
import constants

# Global variable to assign an ID to Oracles
oracle_incremental_idx = 1 

class Oracle:
    def __init__(self, trusted = True) -> None:
        
        # Assign incremental ID
        global oracle_incremental_idx
        self.idx = oracle_incremental_idx
        oracle_incremental_idx += 1

        # Speed goes from 125 to 165 on top of the speed deviation.
        self.avg_speed = constants.ORACLE_BASE_SPEED + constants.ORACLE_MAX_SPEED_DEVIATION * np.random.rand() * 10.0

        self.trusted = trusted
        self.reputation = constants.ORACLE_REPUTATION_INIT
    
    # This function outputs a single partial delay generated by the source
    def generateDelay(self):
        return np.random.normal(self.avg_speed, constants.ORACLE_SPEED_VARIANCE)

    # Average out the last score of the Sources that I queried in the last request
    def updateReputation(self, oracle_consistency_array, total_delay, delay_threshold):

        # Average the scores
        avg_score = np.mean(oracle_consistency_array)

        # Delay component
        score = constants.ORACLE_BETA * utils.constraintFunction(total_delay, delay_threshold) + (1.0 - constants.ORACLE_BETA) * avg_score

        # Update the reputation
        self.reputation = score * constants.ORACLE_ALPHA + self.reputation * (1.0 - constants.ORACLE_ALPHA)

    def print_self(self, verbose=False):
        head = "Trusted" if self.trusted else "Unstrusted"
        print(str(self.idx) + " - " + head + " - " + str(round(self.reputation * 100, 1)))
        return