import numpy as np
import utils

# How much a new value is important over the history of old values (between 0 and 1)
ALPHA = 0.5

# How much the delay counts in calculating the score versus the consistency 
BETA_ORACLE = 0.25

# This is the maximum speed (minimum avg ms taken for an Oracle to query a Producer)
BASE_SPEED = 125.0
MAX_SPEED_DEVIATION = 4.0
SPEED_VARIANCE = 10.0

# if the fastest oracle takes X, then this number is a number Y such that X/Y is the maximum tolerated delay for oracles
SPEED_THRESHOLD_RATIO = 10.0

# Global variable to assign an ID to Oracles
oracle_incremental_idx = 1 

# Initial reputation of a new oracle
ORACLE_REPUTATION_INIT = 0

# Oracles Master Dictionary
Oracles = {}

# Factory
def generateNewOracle(trusted = True):
    """ Factory method to generate a new Oracle and add it to the Oracles dictionary. """
    _oracle = Oracle(trusted)
    Oracles[_oracle.idx] = _oracle
    return _oracle.idx

class Oracle:

    # Oracle is a passive unit
    def __init__(self, trusted = True) -> None:
        
        # Assign incremental ID
        global oracle_incremental_idx
        self.idx = oracle_incremental_idx
        oracle_incremental_idx += 1

        # Speed goes from 125 to 165 on top of the speed deviation.
        self.avg_speed = BASE_SPEED + MAX_SPEED_DEVIATION * np.random.rand() * 10.0

        self.trusted = trusted

        self.scores = []
        self.reputation = ORACLE_REPUTATION_INIT
    
    # This function outputs a single partial delay generated by the sourcescore
    def generateDelay(self):
        return np.random.normal(self.avg_speed, SPEED_VARIANCE)
    
    def record_score(self, oracle_consistency_array, total_delay, delay_threshold):
        """
        Record the score of the Oracle based on the consistency and delay.
        
        :param oracle_consistency_array: Array of consistency scores from the oracles.
        :param total_delay: Total delay incurred by the oracles.
        :param delay_threshold: Threshold for acceptable delay.
        """
        # Average the scores
        avg_score = np.mean(oracle_consistency_array)

        # Delay component
        self.scores.append( BETA_ORACLE * utils.constraintFunction(total_delay, delay_threshold) + (1.0 - BETA_ORACLE) * avg_score )

    # Average out the last score of the Sources that I queried in the last request
    def update_reputation(self):
        """
        Update the reputation of the Oracle based on the scores recorded.
        The reputation is updated using a weighted average of the current score and the previous reputation.
        """
        # Update the reputation
        for score in self.scores:
            self.reputation = score * ALPHA + self.reputation * (1.0 - ALPHA)
        # Reset the scores after updating reputation
        self.scores = []

    def print_self(self, verbose=False):
        head = "Trusted" if self.trusted else "Unstrusted"
        print(str(self.idx) + " - " + head + " - " + str(round(self.reputation * 100, 1)))
        return