import numpy as np
import utils

# How much a new value is important over the history of old values (between 0 and 1)
ALPHA = 0.5

# How much the delay counts in calculating the score versus the consistency 
BETA_ORACLE = 0.25

# This is the maximum speed (minimum avg ms taken for an Oracle to query a Producer)
BASE_SPEED = 125.0
MAX_SPEED_DEVIATION = 4.0
SPEED_VARIANCE = 10.0

# if the fastest oracle takes X, then this number is a number Y such that X/Y is the maximum tolerated delay for oracles
SPEED_THRESHOLD_RATIO = 10.0

# Global variable to assign an ID to Oracles
oracle_incremental_idx = 1 

# Initial reputation of a new oracle
ORACLE_REPUTATION_INIT = 0

class Oracle:

    # Oracle is a passive unit
    def __init__(self, trusted = True) -> None:
        
        # Assign incremental ID
        global oracle_incremental_idx
        self.idx = oracle_incremental_idx
        oracle_incremental_idx += 1

        # Speed goes from 125 to 165 on top of the speed deviation.
        self.avg_speed = BASE_SPEED + MAX_SPEED_DEVIATION * np.random.rand() * 10.0

        self.trusted = trusted
        self.reputation = ORACLE_REPUTATION_INIT
    
    # This function outputs a single partial delay generated by the source
    def generateDelay(self):
        return np.random.normal(self.avg_speed, SPEED_VARIANCE)

    # Average out the last score of the Sources that I queried in the last request
    def updateReputation(self, oracle_consistency_array, total_delay, delay_threshold):

        # Average the scores
        avg_score = np.mean(oracle_consistency_array)

        # Delay component
        score = BETA_ORACLE * utils.constraintFunction(total_delay, delay_threshold) + (1.0 - BETA_ORACLE) * avg_score

        # Update the reputation
        self.reputation = score * ALPHA + self.reputation * (1.0 - ALPHA)

    def print_self(self, verbose=False):
        head = "Trusted" if self.trusted else "Unstrusted"
        print(str(self.idx) + " - " + head + " - " + str(round(self.reputation * 100, 1)))
        return