from typing import Dict
import constants
import numpy as np
import utils

# Global variable to assign an ID to Sources
source_incremental_idx = 1

# GLOBAL DICTIONARY OF SOURCES

class Source:
    '''
    SOURCE:

    Sources are measuring temperature, the ground truth is 25C°, while the "False truth" is 10C°.
    For the moment, none of the source is defective (outputting null values here and there), we assume all of them are functioning correctly.
    Samples are generated according to a normal distribution around the groud truth and a variance that is assigned randomly to the source at its genesis (from 0 to 4)
    Values are assumed too distant from the ground truth (generating a negative rating) if the distance is more than 3.0C°
    Values are assumed not consistent (generating a negative rating) if the deviation from the mean of their own measures of this round is more than 1.5C°

    - Param:
    The BETA value: How much the score (distance from ground truth) is important in the rating versus the consistency.
    '''

    def __init__(self, trusted = True):

        # Assign incremental ID
        global source_incremental_idx
        self.idx = source_incremental_idx
        source_incremental_idx += 1

        self.trusted = trusted
        self.defective = constants.SOURCE_DEFECTIVE and np.random.rand() < constants.SOURCE_RATIO_DEFECTIVE
        self.set_variance()

        # Speed goes from 125 to 165 on top of the variance. Shittier sensors are also slower
        self.avg_speed = constants.SOURCE_BASE_SPEED + self.variance * 10.0
        
        self.lastGeneratedSample = None
        self.last_request = None
        self.last_score_array = None
        self.last_deviation_array = None
        self.last_consistency_array = None
        self.last_score = None
        self.internal_reputation = constants.SOURCE_SOURCE_REPUTATION_INIT
        return
    
    @property
    def trusted(self) -> bool:
        return self._trusted

    @trusted.setter
    def trusted(self, value: bool) -> None:
        self._trusted = value
        self.set_variance()
            
    def set_variance(self) -> None:
        if self.trusted:
            self.variance = constants.SOURCE_MAX_VARIANCE * np.random.rand()
        else:
            self.variance = constants.SOURCE_MAX_VARIANCE_UNTRUSTED * np.random.rand()
        

    # @IVAN generate sample conditioned by the epoch?
    # Generate a number of data samples around the ground truth
    def generateSample(self, request=None, n_samples=constants.SOURCE_N_SAMPLES, beta=constants.SOURCE_BETA_SOURCE):
        self.last_request = request
        if self.trusted:
            self.lastGeneratedSample = np.random.normal(loc=constants.GROUND_TRUTH, scale=self.variance, size=n_samples)
        else:
            self.lastGeneratedSample = np.random.normal(loc=constants.FALSE_TRUTH, scale=self.variance, size=n_samples)

        # Nullify if unstrusted
        if self.defective:
            for _idx, _x in enumerate(self.lastGeneratedSample):
                if np.random.rand() < constants.SOURCE_NULLIFY_PROB:
                    self.lastGeneratedSample[_idx] = None
        return self.lastGeneratedSample
    
    # This function outputs a single partial delay generated by the source
    def generateDelay(self):
        return np.random.normal(self.avg_speed, constants.SOURCE_SPEED_VARIANCE)
    
    # Update the last_score by calculating a new score using the lastGeneratedSample and the inferred truth
    def updateScore(self, _inferred_truth):
        
        # How much values are distant from the GROUND TRUTH
        self.last_score_array = np.array([ # NaN values handled natively
            utils.constraintFunction(_x, constants.TOLERANCE) for _x in np.absolute(self.lastGeneratedSample - _inferred_truth)
        ])

        # How much values are distant from the LOCAL MEAN
        self.last_deviation_array = np.array([ # NaN values handled natively
            utils.constraintFunction(_x, constants.TOLERANCE) for _x in np.absolute(self.lastGeneratedSample - np.mean(self.lastGeneratedSample))
        ])

        # How much values are distant from the LOCAL MEAN but compared with other Oracles [THIS IS FOR ORACLES!]
        self.last_consistency_array = np.array([ # NaN values handled natively
            utils.constraintFunction(_x, np.std(self.lastGeneratedSample - np.mean(self.lastGeneratedSample))) for _x in np.absolute(self.lastGeneratedSample - np.mean(self.lastGeneratedSample))
        ])

        # Calculate the rating using the new equation balanced by a parameter BETA.
        # INFO: Originally returning the minium (a.k.a. the best)
        # ----> self.last_score = np.min(self.last_score_array)
        self.last_score = ( constants.SOURCE_BETA_SOURCE * np.mean(self.last_score_array) )  + ( (1.0 - constants.SOURCE_BETA_SOURCE) * np.mean(self.last_deviation_array))

        # Update the internal reputation, this may help the INdexer in selecting sources...
        self.internal_reputation = self.last_score * constants.SOURCE_ALPHA_SOURCE + self.internal_reputation * (1 - constants.SOURCE_ALPHA_SOURCE)

    def print_self(self, verbose=False):
        head = "Trusted" if self.trusted else "Unstrusted"
        if not verbose:
            print("PRODUCER: " + str(self.idx) + " - " + head + " - Variance:" + str(self.variance))
        else: 
            print("PRODUCER: " + str(self.idx) + " - " + head + " \n\t Variance: " + str(self.variance)
                 + " \n\t Last Request: " + str(self.last_request)
                 + " \n\t Last Sample: " + str(self.lastGeneratedSample)
                 + " \n\t Last Scores: " + str(self.last_score_array)
                 + " \n\t Last Deviations: " + str(self.last_deviation_array)
                 + " \n\t Last Rating: " + str(self.last_score)
                 + " \n\t Internal Reputation: " + str(self.internal_reputation))

Producers: Dict[int, Source] = {}

# Factory method to create a new source and add it to the Producers
def generateNewProducer(trusted = True):
    _source = Source(trusted)
    Producers[_source.idx] = _source
    return _source.idx